# Site settings
title: Kevin's GitHub Pages Site
author: Kevin
email: your.email@example.com
description: >-
  A short description of your site.
baseurl: "" 
url: "https://sinee-x.github.io/blog" 

# Theme settings
theme: minima

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
